
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rightsizing-tmax-io-v1alpha1-rightsizing
  failurePolicy: Fail
  name: mrightsizing.kb.io
  rules:
  - apiGroups:
    - rightsizing.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rightsizings
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rightsizing-tmax-io-v1alpha1-rightsizingrequest
  failurePolicy: Fail
  name: mrightsizingrequest.kb.io
  rules:
  - apiGroups:
    - rightsizing.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rightsizingrequests
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rightsizing-tmax-io-v1alpha1-rightsizing
  failurePolicy: Fail
  name: vrightsizing.kb.io
  rules:
  - apiGroups:
    - rightsizing.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rightsizings
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rightsizing-tmax-io-v1alpha1-rightsizingrequest
  failurePolicy: Fail
  name: vrightsizingrequest.kb.io
  rules:
  - apiGroups:
    - rightsizing.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rightsizingrequests
  sideEffects: None
