# permissions for end users to view rightsizings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rightsizing-viewer-role
rules:
- apiGroups:
  - rightsizing.tmax.io
  resources:
  - rightsizings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rightsizing.tmax.io
  resources:
  - rightsizings/status
  verbs:
  - get
