// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastResult) DeepCopyInto(out *ForecastResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastResult.
func (in *ForecastResult) DeepCopy() *ForecastResult {
	if in == nil {
		return nil
	}
	out := new(ForecastResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationResult) DeepCopyInto(out *OptimizationResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationResult.
func (in *OptimizationResult) DeepCopy() *OptimizationResult {
	if in == nil {
		return nil
	}
	out := new(OptimizationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusQuery) DeepCopyInto(out *PrometheusQuery) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Optimization != nil {
		in, out := &in.Optimization, &out.Optimization
		*out = new(bool)
		**out = **in
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusQuery.
func (in *PrometheusQuery) DeepCopy() *PrometheusQuery {
	if in == nil {
		return nil
	}
	out := new(PrometheusQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryCondition) DeepCopyInto(out *QueryCondition) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryCondition.
func (in *QueryCondition) DeepCopy() *QueryCondition {
	if in == nil {
		return nil
	}
	out := new(QueryCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryConditionOption) DeepCopyInto(out *QueryConditionOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryConditionOption.
func (in *QueryConditionOption) DeepCopy() *QueryConditionOption {
	if in == nil {
		return nil
	}
	out := new(QueryConditionOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryParam) DeepCopyInto(out *QueryParam) {
	*out = *in
	if in.PrometheusUri != nil {
		in, out := &in.PrometheusUri, &out.PrometheusUri
		*out = new(string)
		**out = **in
	}
	if in.Optimization != nil {
		in, out := &in.Optimization, &out.Optimization
		*out = new(bool)
		**out = **in
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryParam.
func (in *QueryParam) DeepCopy() *QueryParam {
	if in == nil {
		return nil
	}
	out := new(QueryParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResult) DeepCopyInto(out *QueryResult) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
	in.RecordedTime.DeepCopyInto(&out.RecordedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResult.
func (in *QueryResult) DeepCopy() *QueryResult {
	if in == nil {
		return nil
	}
	out := new(QueryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQueryConfig) DeepCopyInto(out *ResourceQueryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQueryConfig.
func (in *ResourceQueryConfig) DeepCopy() *ResourceQueryConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceQueryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultData) DeepCopyInto(out *ResultData) {
	*out = *in
	if in.ForecastResult != nil {
		in, out := &in.ForecastResult, &out.ForecastResult
		*out = new(string)
		**out = **in
	}
	if in.OptimizationResult != nil {
		in, out := &in.OptimizationResult, &out.OptimizationResult
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultData.
func (in *ResultData) DeepCopy() *ResultData {
	if in == nil {
		return nil
	}
	out := new(ResultData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultItem) DeepCopyInto(out *ResultItem) {
	*out = *in
	if in.ForecastResult != nil {
		in, out := &in.ForecastResult, &out.ForecastResult
		*out = new(ForecastResult)
		**out = **in
	}
	if in.OptimizationResult != nil {
		in, out := &in.OptimizationResult, &out.OptimizationResult
		*out = new(OptimizationResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultItem.
func (in *ResultItem) DeepCopy() *ResultItem {
	if in == nil {
		return nil
	}
	out := new(ResultItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rightsizing) DeepCopyInto(out *Rightsizing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rightsizing.
func (in *Rightsizing) DeepCopy() *Rightsizing {
	if in == nil {
		return nil
	}
	out := new(Rightsizing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rightsizing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingConfig) DeepCopyInto(out *RightsizingConfig) {
	*out = *in
	out.PrometheusConfig = in.PrometheusConfig
	out.QueryConfig = in.QueryConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingConfig.
func (in *RightsizingConfig) DeepCopy() *RightsizingConfig {
	if in == nil {
		return nil
	}
	out := new(RightsizingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingList) DeepCopyInto(out *RightsizingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rightsizing, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingList.
func (in *RightsizingList) DeepCopy() *RightsizingList {
	if in == nil {
		return nil
	}
	out := new(RightsizingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingQueryConfig) DeepCopyInto(out *RightsizingQueryConfig) {
	*out = *in
	out.ResourceQueries = in.ResourceQueries
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingQueryConfig.
func (in *RightsizingQueryConfig) DeepCopy() *RightsizingQueryConfig {
	if in == nil {
		return nil
	}
	out := new(RightsizingQueryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRequest) DeepCopyInto(out *RightsizingRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRequest.
func (in *RightsizingRequest) DeepCopy() *RightsizingRequest {
	if in == nil {
		return nil
	}
	out := new(RightsizingRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRequestConfig) DeepCopyInto(out *RightsizingRequestConfig) {
	*out = *in
	out.PrometheusConfig = in.PrometheusConfig
	out.QueryConfig = in.QueryConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRequestConfig.
func (in *RightsizingRequestConfig) DeepCopy() *RightsizingRequestConfig {
	if in == nil {
		return nil
	}
	out := new(RightsizingRequestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRequestList) DeepCopyInto(out *RightsizingRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RightsizingRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRequestList.
func (in *RightsizingRequestList) DeepCopy() *RightsizingRequestList {
	if in == nil {
		return nil
	}
	out := new(RightsizingRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizingRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRequestSpec) DeepCopyInto(out *RightsizingRequestSpec) {
	*out = *in
	in.QueryParam.DeepCopyInto(&out.QueryParam)
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]PrometheusQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRequestSpec.
func (in *RightsizingRequestSpec) DeepCopy() *RightsizingRequestSpec {
	if in == nil {
		return nil
	}
	out := new(RightsizingRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingRequestStatus) DeepCopyInto(out *RightsizingRequestStatus) {
	*out = *in
	if in.QueryStatuses != nil {
		in, out := &in.QueryStatuses, &out.QueryStatuses
		*out = make(map[string]QueryCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.QueryResults != nil {
		in, out := &in.QueryResults, &out.QueryResults
		*out = make(map[string]QueryResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingRequestStatus.
func (in *RightsizingRequestStatus) DeepCopy() *RightsizingRequestStatus {
	if in == nil {
		return nil
	}
	out := new(RightsizingRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingSpec) DeepCopyInto(out *RightsizingSpec) {
	*out = *in
	in.QueryParam.DeepCopyInto(&out.QueryParam)
	if in.Trace != nil {
		in, out := &in.Trace, &out.Trace
		*out = new(bool)
		**out = **in
	}
	if in.TraceCycle != nil {
		in, out := &in.TraceCycle, &out.TraceCycle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingSpec.
func (in *RightsizingSpec) DeepCopy() *RightsizingSpec {
	if in == nil {
		return nil
	}
	out := new(RightsizingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizingStatus) DeepCopyInto(out *RightsizingStatus) {
	*out = *in
	if in.ServiceStatuses != nil {
		in, out := &in.ServiceStatuses, &out.ServiceStatuses
		*out = make(map[string]QueryCondition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ServiceResults != nil {
		in, out := &in.ServiceResults, &out.ServiceResults
		*out = make(map[string]QueryResult, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizingStatus.
func (in *RightsizingStatus) DeepCopy() *RightsizingStatus {
	if in == nil {
		return nil
	}
	out := new(RightsizingStatus)
	in.DeepCopyInto(out)
	return out
}
