apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: rightsizing-trace-manager
  labels:
    rightsizing: trace
spec:
  selector:
    matchLabels:
      rightsizing: trace
  replicas: 1
  template:
    metadata:
      labels:
        rightsizing: trace
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /trace
          args:
            - --test
          image: dbdydgur2244/rightsizing-controller:latest
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10